version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hotel

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
