version: "3.8"

services:
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"  # Expose FastAPI app on port 8000
    env_file:
      - ./app/.env   # Load environment variables
    depends_on:
      - mongo         # Ensure MongoDB starts before the app
    volumes:
      - ./app:/app    # Sync local code with the container
    container_name: fastapi_app

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    volumes:
      - mongo_data:/data/db
    container_name: mongodb

volumes:
  mongo_data:
